-- ============================================
-- UKPBJ Kabupaten Bungo - Schema Konten
-- Fokus: Panduan, Regulasi, Pengumuman
-- ============================================
-- Jalankan di Supabase SQL Editor (project: isnojgpcmwsjcfcgbndr)
-- Kredensial (.env):
--   VITE_SUPABASE_URL      = https://isnojgpcmwsjcfcgbndr.supabase.co
--   VITE_SUPABASE_ANON_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
--
-- Tabel yang dibuat:
--   Panduan    : guide_categories, guides, guide_videos
--   Regulasi   : regulations
--   Pengumuman : announcements
-- ============================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- PANDAAN
-- ============================================

-- Kategori panduan
CREATE TABLE IF NOT EXISTS guide_categories (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_guide_categories_slug ON guide_categories(slug);

-- Panduan (PDF)
CREATE TABLE IF NOT EXISTS guides (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  content TEXT,
  role TEXT NOT NULL CHECK (role IN ('PPK', 'Vendor', 'Pokja', 'Admin', 'Semua', 'Pejabat Pengadaan', 'PA', 'Penyedia')),
  category TEXT NOT NULL DEFAULT 'Panduan Inaproc' CHECK (category IN ('Panduan Inaproc', 'Panduan LPSE')),
  file_url TEXT,
  file_size TEXT,
  file_type TEXT DEFAULT 'pdf',
  image_url TEXT,
  is_featured BOOLEAN DEFAULT false,
  is_published BOOLEAN DEFAULT true,
  view_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_guides_role ON guides(role);
CREATE INDEX IF NOT EXISTS idx_guides_category ON guides(category);
CREATE INDEX IF NOT EXISTS idx_guides_published ON guides(is_published);
CREATE INDEX IF NOT EXISTS idx_guides_featured ON guides(is_featured);

-- Sinkronisasi constraint role (idempoten, aman dijalankan ulang)
ALTER TABLE guides DROP CONSTRAINT IF EXISTS guides_role_check;
ALTER TABLE guides ADD CONSTRAINT guides_role_check
  CHECK (role IN ('PPK', 'Vendor', 'Pokja', 'Admin', 'Semua', 'Pejabat Pengadaan', 'PA', 'Penyedia'));

-- Video tutorial
CREATE TABLE IF NOT EXISTS guide_videos (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  guide_id UUID REFERENCES guides(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  video_url TEXT NOT NULL,
  thumbnail_url TEXT,
  duration TEXT,
  category TEXT NOT NULL DEFAULT 'Panduan Inaproc' CHECK (category IN ('Panduan Inaproc', 'Panduan LPSE')),
  role TEXT[] NOT NULL DEFAULT '{PPK}' CHECK (role <@ ARRAY['PPK', 'Pejabat Pengadaan', 'Pokja', 'PA', 'Penyedia']::TEXT[]),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_guide_videos_category ON guide_videos(category);
CREATE INDEX IF NOT EXISTS idx_guide_videos_role ON guide_videos(role);

-- ============================================
-- REGULASI
-- ============================================
CREATE TABLE IF NOT EXISTS regulations (
  id bigint generated by default as identity not null,
  nomor text not null,
  tahun text,
  judul text,
  status text DEFAULT 'Berlaku' CHECK (status IN ('Berlaku', 'Dicabut', 'Draft')),
  document_url text,
  type text,
  description text,
  category text,
  publish_date text,
  is_published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) not null,
  constraint regulations_pkey primary key (id)
);
CREATE INDEX IF NOT EXISTS idx_regulations_tahun ON regulations(tahun);
CREATE INDEX IF NOT EXISTS idx_regulations_status ON regulations(status);
CREATE INDEX IF NOT EXISTS idx_regulations_published ON regulations(is_published);

-- ============================================
-- PENGUMUMAN
-- ============================================
CREATE TABLE IF NOT EXISTS announcements (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL,
  badge TEXT NOT NULL,
  badge_class TEXT NOT NULL,
  date TEXT NOT NULL,
  detail_date TEXT NOT NULL,
  category TEXT NOT NULL,
  author TEXT NOT NULL,
  image_url TEXT NOT NULL,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_announcements_published ON announcements(is_published);
CREATE INDEX IF NOT EXISTS idx_announcements_created_at ON announcements(created_at DESC);

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================
ALTER TABLE guides ENABLE ROW LEVEL SECURITY;
ALTER TABLE guide_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE guide_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE regulations ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view published guides" ON guides
  FOR SELECT USING (is_published = true);
CREATE POLICY "Public can view guide categories" ON guide_categories
  FOR SELECT USING (true);
CREATE POLICY "Public can view guide videos" ON guide_videos
  FOR SELECT USING (true);
CREATE POLICY "Public can view published regulations" ON regulations
  FOR SELECT USING (is_published = true);
CREATE POLICY "Public can view published announcements" ON announcements
  FOR SELECT USING (is_published = true);

-- Izinkan insert regulations dari anon key (untuk seed script)
DROP POLICY IF EXISTS "Public can insert regulations" ON regulations;
CREATE POLICY "Public can insert regulations" ON regulations
  FOR INSERT WITH CHECK (true);

-- ============================================
-- SEED DATA
-- ============================================

-- Panduan: kategori
INSERT INTO guide_categories (name, slug, description, icon) VALUES
  ('PPK', 'ppk', 'Panduan untuk Pejabat Pembuat Komitmen', 'person'),
  ('Vendor', 'vendor', 'Panduan untuk Penyedia/Vendor', 'business'),
  ('Pokja', 'pokja', 'Panduan untuk Pokja Pemilihan', 'groups'),
  ('Admin', 'admin', 'Panduan untuk Admin LPSE', 'admin_panel_settings'),
  ('Umum', 'umum', 'Panduan umum untuk semua pengguna', 'public')
ON CONFLICT (slug) DO NOTHING;

-- Panduan: guides
INSERT INTO guides (title, description, content, role, category, file_url, file_size, is_featured, is_published) VALUES
  ('Buku Saku Digital: Prosedur Pengadaan Barang/Jasa Pemerintah 2024', 'Panduan komprehensif mengenai tata cara terbaru proses pengadaan mulai dari perencanaan hingga serah terima hasil pekerjaan.', 'Panduan komprehensif prosedur pengadaan Barang/Jasa Pemerintah tahun 2024.', 'PPK', 'Panduan Inaproc', '/docs/buku-saku-prosedur-pengadaan-2024.pdf', '4.8 MB', true, true),
  ('Panduan Pendaftaran Akun SIKaP', 'Langkah-langkah lengkap melakukan pendaftaran dan verifikasi profil badan usaha di Sistem Informasi Kinerja Penyedia.', 'Langkah pendaftaran dan verifikasi akun SIKaP untuk penyedia.', 'Vendor', 'Panduan Inaproc', '/docs/panduan-pendaftaran-sikap.pdf', '2.1 MB', false, true),
  ('Tata Cara Evaluasi Dokumen Penawaran', 'Modul teknis evaluasi kualifikasi, administrasi, teknis, dan harga untuk Pokja Pemilihan di aplikasi SPSE.', 'Modul evaluasi dokumen penawaran untuk Pokja.', 'Pokja', 'Panduan Inaproc', '/docs/tata-cara-evaluasi-penawaran.pdf', '3.4 MB', false, true),
  ('Penyusunan HPS & Spesifikasi Teknis', 'Pedoman perhitungan Harga Perkiraan Sendiri (HPS) yang akuntabel sesuai dengan regulasi LKPP terbaru.', 'Pedoman penyusunan HPS dan spesifikasi teknis.', 'PPK', 'Panduan Inaproc', '/docs/penyusunan-hps-spesifikasi.pdf', '2.7 MB', false, true),
  ('Panduan Operasional SPSE v4.5 untuk Pengguna', 'Dokumen panduan komprehensif mengenai tata cara penggunaan Sistem Pengadaan Secara Elektronik (SPSE) versi 4.5.', 'Panduan operasional SPSE v4.5 untuk Pejabat Pengadaan dan Penyedia.', 'Pejabat Pengadaan', 'Panduan LPSE', '/docs/panduan-operasional-spse-v45.pdf', '12.4 MB', true, true)
ON CONFLICT DO NOTHING;

-- Panduan: video tutorial
INSERT INTO guide_videos (title, description, video_url, thumbnail_url, duration, category, role) VALUES
  ('Tutorial Pendaftaran Penyedia di SIKaP', 'Video panduan pendaftaran akun penyedia barang/jasa.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', '', '08:32', 'Panduan Inaproc', '{Vendor}'),
  ('Cara Mengikuti Tender di SPSE', 'Langkah-langkah mengikuti tender elektronik.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', '', '12:45', 'Panduan Inaproc', '{PPK, Pokja}'),
  ('Evaluasi Penawaran & Penetapan Pemenang', 'Modul evaluasi penawaran dan penetapan pemenang.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', '', '12:45', 'Panduan LPSE', '{Pejabat Pengadaan, Pokja}')
ON CONFLICT DO NOTHING;

-- Regulasi
INSERT INTO regulations (nomor, tahun, judul, type, status, description, category, document_url, publish_date) VALUES
  ('Perpres No. 12', '2021', 'Perubahan atas Perpres No. 16 Tahun 2018 tentang Pengadaan Barang/Jasa Pemerintah', 'Peraturan Presiden (PERPRES)', 'Berlaku', 'Peraturan presiden yang mengubah beberapa ketentuan dalam Perpres No. 16 Tahun 2018.', 'Peraturan Presiden', '/docs/perpres-no-12-tahun-2021.pdf', '2021-02-10'),
  ('Perpres No. 16', '2018', 'Pengadaan Barang/Jasa Pemerintah', 'Peraturan Presiden (PERPRES)', 'Dicabut', 'Peraturan presiden tentang pengadaan barang/jasa pemerintah yang kemudian diubah oleh Perpres No. 12 Tahun 2021.', 'Peraturan Presiden', '/docs/perpres-no-16-tahun-2018.pdf', '2018-10-17'),
  ('Perka LKPP No. 12', '2021', 'Pedoman Pelaksanaan Pengadaan Barang/Jasa Pemerintah Melalui Penyedia', 'Peraturan Lembaga Kebijakan Pengadaan (PERKA)', 'Berlaku', 'Pedoman pelaksanaan pengadaan barang/jasa pemerintah melalui penyedia barang/jasa.', 'Peraturan LKPP', '/docs/perka-lkpp-no-12-tahun-2021.pdf', '2021-03-15'),
  ('Inpres No. 2', '2022', 'Percepatan Peningkatan Penggunaan Produk Dalam Negeri dan Produk Usaha Mikro', 'Instruksi Presiden (INPRES)', 'Berlaku', 'Instruksi presiden untuk percepatan peningkatan penggunaan produk dalam negeri dan produk usaha mikro.', 'Instruksi Presiden', '/docs/inpres-no-2-tahun-2022.pdf', '2022-01-05'),
  ('Perka LKPP No. 7', '2023', 'Pedoman Pengadaan Barang/Jasa Pemerintah untuk Pengguna Anggaran', 'Peraturan Lembaga Kebijakan Pengadaan (PERKA)', 'Berlaku', 'Pedoman pengadaan barang/jasa pemerintah untuk pengguna anggaran.', 'Peraturan LKPP', '/docs/perka-lkpp-no-7-tahun-2023.pdf', '2023-06-20'),
  ('Perpres No. 27', '2023', 'Perubahan atas Perpres No. 12 Tahun 2021 tentang Pengadaan Barang/Jasa Pemerintah', 'Peraturan Presiden (PERPRES)', 'Berlaku', 'Peraturan presiden yang mengubah beberapa ketentuan dalam Perpres No. 12 Tahun 2021.', 'Peraturan Presiden', '/docs/perpres-no-27-tahun-2023.pdf', '2023-08-14'),
  ('Perka LKPP No. 3', '2024', 'Pedoman Pengadaan Barang/Jasa Pemerintah Melalui Tender', 'Peraturan Lembaga Kebijakan Pengadaan (PERKA)', 'Berlaku', 'Pedoman pengadaan barang/jasa pemerintah melalui tender.', 'Peraturan LKPP', '/docs/perka-lkpp-no-3-tahun-2024.pdf', '2024-01-22'),
  ('Perpres No. 5', '2024', 'Pengadaan Barang/Jasa Pemerintah Tahun 2024', 'Peraturan Presiden (PERPRES)', 'Berlaku', 'Peraturan presiden tentang pengadaan barang/jasa pemerintah tahun 2024.', 'Peraturan Presiden', '/docs/perpres-no-5-tahun-2024.pdf', '2024-02-28'),
  ('Perpres No. 14', '2017', 'Perubahan atas Perpres No. 70 Tahun 2012 tentang Pengadaan Barang/Jasa Pemerintah', 'Peraturan Presiden (PERPRES)', 'Dicabut', 'Peraturan presiden yang mengubah beberapa ketentuan dalam Perpres No. 70 Tahun 2012, yang kemudian dicabut dan diganti oleh Perpres No. 16 Tahun 2018.', 'Peraturan Presiden', '/docs/perpres-no-14-tahun-2017.pdf', '2017-07-26'),
  ('Perka LKPP No. 10', '2021', 'Pedoman Pengadaan Barang/Jasa Pemerintah Melalui Pengadaan Langsung', 'Peraturan Lembaga Kebijakan Pengadaan (PERKA)', 'Berlaku', 'Pedoman pelaksanaan pengadaan barang/jasa pemerintah melalui pengadaan langsung.', 'Peraturan LKPP', '/docs/perka-lkpp-no-10-tahun-2021.pdf', '2021-04-12'),
  ('Perka LKPP No. 11', '2021', 'Pedoman Pengadaan Barang/Jasa Pemerintah Melalui Penunjukkan Langsung', 'Peraturan Lembaga Kebijakan Pengadaan (PERKA)', 'Berlaku', 'Pedoman pelaksanaan pengadaan barang/jasa pemerintah melalui penunjukkan langsung.', 'Peraturan LKPP', '/docs/perka-lkpp-no-11-tahun-2021.pdf', '2021-04-12'),
  ('Perka LKPP No. 5', '2022', 'Pedoman Pengadaan Barang/Jasa Pemerintah untuk Pengguna Anggaran', 'Peraturan Lembaga Kebijakan Pengadaan (PERKA)', 'Berlaku', 'Pedoman pengadaan barang/jasa pemerintah untuk pengguna anggaran.', 'Peraturan LKPP', '/docs/perka-lkpp-no-5-tahun-2022.pdf', '2022-03-18'),
  ('Perka LKPP No. 8', '2023', 'Pedoman Pengadaan Barang/Jasa Pemerintah Melalui Swakelola', 'Peraturan Lembaga Kebijakan Pengadaan (PERKA)', 'Berlaku', 'Pedoman pelaksanaan pengadaan barang/jasa pemerintah melalui swakelola.', 'Peraturan LKPP', '/docs/perka-lkpp-no-8-tahun-2023.pdf', '2023-05-22'),
  ('Perpres No. 19', '2023', 'Perubahan atas Perpres No. 27 Tahun 2023 tentang Pengadaan Barang/Jasa Pemerintah', 'Peraturan Presiden (PERPRES)', 'Berlaku', 'Peraturan presiden yang mengubah beberapa ketentuan dalam Perpres No. 27 Tahun 2023.', 'Peraturan Presiden', '/docs/perpres-no-19-tahun-2023.pdf', '2023-10-05'),
  ('Perka LKPP No. 6', '2024', 'Pedoman Pengadaan Barang/Jasa Pemerintah Melalui E-Katalog', 'Peraturan Lembaga Kebijakan Pengadaan (PERKA)', 'Berlaku', 'Pedoman pelaksanaan pengadaan barang/jasa pemerintah melalui e-katalog.', 'Peraturan LKPP', '/docs/perka-lkpp-no-6-tahun-2024.pdf', '2024-03-11'),
  ('Perpres No. 10', '2024', 'Perubahan atas Perpres No. 5 Tahun 2024 tentang Pengadaan Barang/Jasa Pemerintah', 'Peraturan Presiden (PERPRES)', 'Berlaku', 'Peraturan presiden yang mengubah beberapa ketentuan dalam Perpres No. 5 Tahun 2024.', 'Peraturan Presiden', '/docs/perpres-no-10-tahun-2024.pdf', '2024-04-15')
ON CONFLICT DO NOTHING;

-- Pengumuman
INSERT INTO announcements (title, excerpt, content, badge, badge_class, date, detail_date, category, author, image_url, is_published) VALUES
  ('Pembaruan Sistem Keamanan SPSE Versi 4.5 Patch 2024', 'Sehubungan dengan adanya pemeliharaan rutin dan peningkatan fitur keamanan pada server produksi, kami informasikan bahwa akan dilakukan downtime terjadwal.', 'Yth. Para Pengguna Layanan Pengadaan Secara Elektronik (LPSE),\n\nDalam rangka meningkatkan kualitas layanan dan keamanan transaksi elektronik pada aplikasi SPSE, kami informasikan bahwa akan dilaksanakan pemeliharaan sistem pada:\n- Hari/Tanggal: Sabtu, 25 Mei 2024\n- Waktu: 22.00 WIB s.d Minggu, 26 Mei 2024 04.00 WIB\n- Agenda: Penerapan Security Patch 2024 dan Optimasi Database\n\nSelama proses pemeliharaan tersebut, aplikasi SPSE tidak dapat diakses untuk sementara waktu.', 'Sistem', 'bg-secondary text-on-secondary', '24 Mei 2024', '24 Mei 2024, 09:15 WIB', 'Informasi Teknis', 'Admin Pusat', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDv-qSF15SKFJdSUvsDnEqeFCVMDEh4mHRjzlQhQNd6YJhhSjezne0R4cM-ZLMSADR68PbOHGSMyCLGlfCnvy06iQZ_y6QZvWqgyvD-esGXCMwc5otWOAqc6cwZPl5VRApS0YIWuqPAH7FtewR99hhIsPtp1dC6uf7KJsp7VvEEQEmcRqwxxioEf7x8ZUeNuYXOX6GXiOkyN9kzXF4YNU7aeCOSPtmRZRzZjevCn2QTunDdBry9CbwIjPP39gm_vdPmHOn39h67BKGJ', true),
  ('Pemberlakuan Peraturan LKPP Baru Terkait E-Purchasing', 'LKPP resmi merilis aturan turunan mengenai tata cara pembelian elektronik melalui katalog nasional untuk meningkatkan efisiensi belanja negara.', 'Dalam rangka mendukung keterbukaan pasar pengadaan barang/jasa pemerintah, LKPP merilis modul pendaftaran bagi entitas asing yang ingin berpartisipasi dalam Katalog Elektronik Sektoral maupun Nasional.', 'Regulasi', 'bg-primary text-on-primary', '21 Mei 2024', '21 Mei 2024, 14:30 WIB', 'Regulasi', 'Divisi Katalog', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDXXB87V5oiS3-o7jAwboE-fcbq4yUcUsrxrj2v-HiJIrXezZCH1_tdJ5w3x1DzpS9xIIOts10KLk62FlCGi6CqV86bXPMmzMQfGxzrfiA-P7KSxt4ctnkj2jSSzF_kZZTvcwxX0XefjtG2o_VnmBzY7EhRspV_60Esplc9aZv9Ro1koWtGme8LftXLETe6EXjtUy5I-7FcnxDen77_IgiIb-hZZ2xNzgRX4_ru7oDnFp-yeLLdi7L69bOzC_EjrdUAC7euw3uOYSIW', true),
  ('Sosialisasi Penggunaan Portal Inaproc Versi Terbaru 2024', 'Undangan sosialisasi daring untuk Pejabat Pembuat Komitmen (PPK) mengenai fitur-fitur baru pada Dashboard monitoring Inaproc.', 'Kami mengundang seluruh Pejabat Pembuat Komitmen (PPK) untuk menghadiri sesi daring mengenai implementasi mitigasi risiko pada proses tender konstruksi pasca terbitnya Perlem No 12.', 'Kegiatan', 'bg-tertiary-container text-on-tertiary-container', '18 Mei 2024', '18 Mei 2024, 10:00 WIB', 'Kegiatan', 'Biro Pelatihan', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQm5Kd9uLy0TSXbPXAbyAERpnQiCXH2ory58HASxVMR0ul1SaAu0EaJSlUSuJoyidoKy4W_8BwPDqvCCesQ0ivRLjAUlRJM33h2qp2O1H2h6BppKvfV_4aXGCIpOXGPI3vQ-YG4n7A3yY6txARUQe345oGPS9LrJscmYTTswlnXEJB4bzl4pimDCbZ_MZ1JeSvj9tNVCCrtjUJ1HkyNsdBfZ-UnFu-ZpSf9Rylxf__CBecZVxvs-Q5M8UXMzLQSWT7LBn0M_lq_oqa', true)
ON CONFLICT DO NOTHING;
