/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#0058be',
        'on-secondary-fixed': '#001a42',
        'surface-container': '#e6eeff',
        'on-secondary': '#ffffff',
        'primary-fixed': '#dce1ff',
        'surface-container-high': '#dee9fc',
        'secondary-container': '#2170e4',
        'inverse-on-surface': '#eaf1ff',
        primary: '#00236f',
        'tertiary-fixed': '#ffdbcb',
        'on-error': '#ffffff',
        'tertiary-container': '#6e2c00',
        'inverse-primary': '#b6c4ff',
        'on-surface-variant': '#444651',
        'primary-container': '#1e3a8a',
        'surface-bright': '#f8f9ff',
        'on-tertiary-fixed-variant': '#773205',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'on-secondary-container': '#fefcff',
        outline: '#757682',
        'on-tertiary-container': '#f39461',
        'tertiary-fixed-dim': '#ffb691',
        'secondary-fixed': '#d8e2ff',
        'error-container': '#ffdad6',
        'surface-tint': '#4059aa',
        'on-primary-fixed': '#00164e',
        'on-surface': '#121c2a',
        'surface-container-highest': '#d9e3f6',
        'on-primary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-variant': '#d9e3f6',
        'on-secondary-fixed-variant': '#004395',
        'inverse-surface': '#27313f',
        background: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#341100',
        'surface-dim': '#d0dbed',
        'outline-variant': '#c5c5d3',
        'primary-fixed-dim': '#b6c4ff',
        'on-primary-fixed-variant': '#264191',
        surface: '#f8f9ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-background': '#121c2a',
        tertiary: '#4b1c00',
        'on-primary-container': '#90a8ff',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '48px',
        gutter: '24px',
        lg: '24px',
        md: '16px',
        'container-max': '1280px',
        sm: '8px',
        base: '4px',
        xs: '4px',
      },
      fontFamily: {
        'headline-sm': ['Inter'],
        'body-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'display-lg': ['Inter'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
