/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#261900',
        'inverse-on-surface': '#f0f0f3',
        'on-secondary': '#ffffff',
        'on-surface': '#1a1c1e',
        outline: '#747783',
        'surface-variant': '#e2e2e5',
        'secondary-container': '#fed488',
        'on-primary-fixed': '#001947',
        'surface-container-low': '#f3f3f6',
        'tertiary-fixed-dim': '#c1c7d0',
        'on-secondary-fixed-variant': '#5d4201',
        'on-secondary-container': '#785a1a',
        surface: '#f9f9fc',
        'secondary-fixed-dim': '#e9c176',
        'primary-fixed-dim': '#b1c5ff',
        'surface-container-highest': '#e2e2e5',
        'surface-bright': '#f9f9fc',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3c434a',
        'surface-container': '#eeeef0',
        'on-error-container': '#93000a',
        secondary: '#775a19',
        'on-tertiary-container': '#a9afb8',
        background: '#f9f9fc',
        'on-surface-variant': '#434652',
        'tertiary-fixed': '#dde3ec',
        'on-error': '#ffffff',
        tertiary: '#262d33',
        'outline-variant': '#c4c6d3',
        'on-tertiary-fixed': '#161c23',
        'on-background': '#1a1c1e',
        'error-container': '#ffdad6',
        'primary-container': '#0b3d91',
        'primary-fixed': '#dae2ff',
        'surface-dim': '#dadadc',
        'surface-container-lowest': '#ffffff',
        primary: '#002869',
        'on-primary-fixed-variant': '#144296',
        error: '#ba1a1a',
        'on-primary-container': '#8dadff',
        'surface-tint': '#345baf',
        'on-tertiary-fixed-variant': '#41474f',
        'secondary-fixed': '#ffdea5',
        'inverse-primary': '#b1c5ff',
        'surface-container-high': '#e8e8ea',
        'on-primary': '#ffffff',
        'inverse-surface': '#2f3133',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '0.5rem',
        gutter: '1.5rem',
        'stack-lg': '2rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
        'container-max': '1280px',
        'stack-md': '1rem',
        'stack-xs': '0.25rem',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter'],
        'body-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'display-lg': ['Inter'],
        'label-sm': ['Inter'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.25', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
